Console.BackgroundColor = ConsoleColor.White;
Console.Clear();
Console.Write("                  ");
Console.BackgroundColor = ConsoleColor.Black;
Console.WriteLine();
Console.BackgroundColor = ConsoleColor.White;
Console.Write("      ");
Console.BackgroundColor = ConsoleColor.Black;
Console.Write("      ");
Console.BackgroundColor = ConsoleColor.White;
Console.Write("      ");
Console.BackgroundColor = ConsoleColor.Black;
Console.WriteLine();
Console.BackgroundColor = ConsoleColor.White;
Console.Write("    ");
Console.BackgroundColor = ConsoleColor.Black;
Console.Write("  ");
Console.BackgroundColor = ConsoleColor.White;
Console.Write("  ");
Console.BackgroundColor = ConsoleColor.DarkRed;
Console.Write("  ");
Console.BackgroundColor = ConsoleColor.White;
Console.Write("  ");
Console.BackgroundColor = ConsoleColor.Black;
Console.Write("  ");
Console.BackgroundColor = ConsoleColor.White;
Console.Write("    ");
Console.BackgroundColor = ConsoleColor.Black;
Console.WriteLine();
Console.BackgroundColor = ConsoleColor.White;
Console.Write("   ");
Console.BackgroundColor = ConsoleColor.Black;
Console.Write(" ");
Console.BackgroundColor = ConsoleColor.DarkRed;
Console.Write(" ");
Console.BackgroundColor = ConsoleColor.White;
Console.Write("   ");
Console.BackgroundColor = ConsoleColor.DarkRed;
Console.Write("  ");
Console.BackgroundColor = ConsoleColor.White;
Console.Write("   ");
Console.BackgroundColor = ConsoleColor.DarkRed;
Console.Write(" ");
Console.BackgroundColor = ConsoleColor.Black;
Console.Write(" ");
Console.BackgroundColor = ConsoleColor.White;
Console.Write("   ");
Console.BackgroundColor = ConsoleColor.Black;
Console.WriteLine();
Console.BackgroundColor = ConsoleColor.White;
Console.Write("  ");
Console.BackgroundColor = ConsoleColor.Black;
Console.Write(" ");
Console.BackgroundColor = ConsoleColor.DarkRed;
Console.Write("  ");
Console.BackgroundColor = ConsoleColor.White;
Console.Write("  ");
Console.BackgroundColor = ConsoleColor.DarkRed;
Console.Write("    ");
Console.BackgroundColor = ConsoleColor.White;
Console.Write("  ");
Console.BackgroundColor = ConsoleColor.DarkRed;
Console.Write("  ");
Console.BackgroundColor = ConsoleColor.Black;
Console.Write(" ");
Console.BackgroundColor = ConsoleColor.White;
Console.Write("  ");
Console.BackgroundColor = ConsoleColor.Black;
Console.WriteLine();
Console.BackgroundColor = ConsoleColor.White;
Console.Write("  ");
Console.BackgroundColor = ConsoleColor.Black;
Console.Write(" ");
Console.BackgroundColor = ConsoleColor.White;
Console.Write(" ");
Console.BackgroundColor = ConsoleColor.DarkRed;
Console.Write("          ");
Console.BackgroundColor = ConsoleColor.White;
Console.Write(" ");
Console.BackgroundColor = ConsoleColor.Black;
Console.Write(" ");
Console.BackgroundColor = ConsoleColor.White;
Console.Write("  ");
Console.BackgroundColor = ConsoleColor.Black;
Console.WriteLine();
Console.BackgroundColor = ConsoleColor.White;
Console.Write(" ");
Console.BackgroundColor = ConsoleColor.Black;
Console.Write(" ");
Console.BackgroundColor = ConsoleColor.White;
Console.Write("   ");
Console.BackgroundColor = ConsoleColor.DarkRed;
Console.Write("  ");
Console.BackgroundColor = ConsoleColor.White;
Console.Write("    ");
Console.BackgroundColor = ConsoleColor.DarkRed;
Console.Write("  ");
Console.BackgroundColor = ConsoleColor.White;
Console.Write("   ");
Console.BackgroundColor = ConsoleColor.Black;
Console.Write(" ");
Console.BackgroundColor = ConsoleColor.White;
Console.Write(" ");
Console.BackgroundColor = ConsoleColor.Black;
Console.WriteLine();
Console.BackgroundColor = ConsoleColor.White;
Console.Write(" ");
Console.BackgroundColor = ConsoleColor.Black;
Console.Write(" ");
Console.BackgroundColor = ConsoleColor.White;
Console.Write("   ");
Console.BackgroundColor = ConsoleColor.DarkRed;
Console.Write(" ");
Console.BackgroundColor = ConsoleColor.White;
Console.Write("      ");
Console.BackgroundColor = ConsoleColor.DarkRed;
Console.Write(" ");
Console.BackgroundColor = ConsoleColor.White;
Console.Write("   ");
Console.BackgroundColor = ConsoleColor.Black;
Console.Write(" ");
Console.BackgroundColor = ConsoleColor.White;
Console.Write(" ");
Console.BackgroundColor = ConsoleColor.Black;
Console.WriteLine();
Console.BackgroundColor = ConsoleColor.White;
Console.Write(" ");
Console.BackgroundColor = ConsoleColor.Black;
Console.Write(" ");
Console.BackgroundColor = ConsoleColor.White;
Console.Write("   ");
Console.BackgroundColor = ConsoleColor.DarkRed;
Console.Write(" ");
Console.BackgroundColor = ConsoleColor.White;
Console.Write("      ");
Console.BackgroundColor = ConsoleColor.DarkRed;
Console.Write(" ");
Console.BackgroundColor = ConsoleColor.White;
Console.Write("   ");
Console.BackgroundColor = ConsoleColor.Black;
Console.Write(" ");
Console.BackgroundColor = ConsoleColor.White;
Console.Write(" ");
Console.BackgroundColor = ConsoleColor.Black;
Console.WriteLine();
Console.BackgroundColor = ConsoleColor.White;
Console.Write(" ");
Console.BackgroundColor = ConsoleColor.Black;
Console.Write(" ");
Console.BackgroundColor = ConsoleColor.White;
Console.Write("  ");
Console.BackgroundColor = ConsoleColor.DarkRed;
Console.Write("   ");
Console.BackgroundColor = ConsoleColor.White;
Console.Write("    ");
Console.BackgroundColor = ConsoleColor.DarkRed;
Console.Write("   ");
Console.BackgroundColor = ConsoleColor.White;
Console.Write("  ");
Console.BackgroundColor = ConsoleColor.Black;
Console.Write(" ");
Console.BackgroundColor = ConsoleColor.White;
Console.Write(" ");
Console.BackgroundColor = ConsoleColor.Black;
Console.WriteLine();
Console.BackgroundColor = ConsoleColor.White;
Console.Write(" ");
Console.BackgroundColor = ConsoleColor.Black;
Console.Write(" ");
Console.BackgroundColor = ConsoleColor.DarkRed;
Console.Write("      ");
Console.BackgroundColor = ConsoleColor.White;
Console.Write("  ");
Console.BackgroundColor = ConsoleColor.DarkRed;
Console.Write("      ");
Console.BackgroundColor = ConsoleColor.Black;
Console.Write(" ");
Console.BackgroundColor = ConsoleColor.White;
Console.Write(" ");
Console.BackgroundColor = ConsoleColor.Black;
Console.WriteLine();
Console.BackgroundColor = ConsoleColor.White;
Console.Write(" ");
Console.BackgroundColor = ConsoleColor.Black;
Console.Write(" ");
Console.BackgroundColor = ConsoleColor.DarkRed;
Console.Write("  ");
Console.BackgroundColor = ConsoleColor.Black;
Console.Write("          ");
Console.BackgroundColor = ConsoleColor.DarkRed;
Console.Write("  ");
Console.BackgroundColor = ConsoleColor.Black;
Console.Write(" ");
Console.BackgroundColor = ConsoleColor.White;
Console.Write(" ");
Console.BackgroundColor = ConsoleColor.Black;
Console.WriteLine();
Console.BackgroundColor = ConsoleColor.White;
Console.Write("  ");
Console.BackgroundColor = ConsoleColor.Black;
Console.Write("   ");
Console.BackgroundColor = ConsoleColor.White;
Console.Write("  ");
Console.BackgroundColor = ConsoleColor.Black;
Console.Write(" ");
Console.BackgroundColor = ConsoleColor.White;
Console.Write("  ");
Console.BackgroundColor = ConsoleColor.Black;
Console.Write(" ");
Console.BackgroundColor = ConsoleColor.White;
Console.Write("  ");
Console.BackgroundColor = ConsoleColor.Black;
Console.Write("   ");
Console.BackgroundColor = ConsoleColor.White;
Console.Write("  ");
Console.BackgroundColor = ConsoleColor.Black;
Console.WriteLine();
Console.BackgroundColor = ConsoleColor.White;
Console.Write("   ");
Console.BackgroundColor = ConsoleColor.Black;
Console.Write(" ");
Console.BackgroundColor = ConsoleColor.White;
Console.Write("   ");
Console.BackgroundColor = ConsoleColor.Black;
Console.Write(" ");
Console.BackgroundColor = ConsoleColor.White;
Console.Write("  ");
Console.BackgroundColor = ConsoleColor.Black;
Console.Write(" ");
Console.BackgroundColor = ConsoleColor.White;
Console.Write("   ");
Console.BackgroundColor = ConsoleColor.Black;
Console.Write(" ");
Console.BackgroundColor = ConsoleColor.White;
Console.Write("   ");
Console.BackgroundColor = ConsoleColor.Black;
Console.WriteLine();
Console.BackgroundColor = ConsoleColor.White;
Console.Write("   ");
Console.BackgroundColor = ConsoleColor.Black;
Console.Write(" ");
Console.BackgroundColor = ConsoleColor.White;
Console.Write("          ");
Console.BackgroundColor = ConsoleColor.Black;
Console.Write(" ");
Console.BackgroundColor = ConsoleColor.White;
Console.Write("   ");
Console.BackgroundColor = ConsoleColor.Black;
Console.WriteLine();
Console.BackgroundColor = ConsoleColor.White;
Console.Write("    ");
Console.BackgroundColor = ConsoleColor.Black;
Console.Write(" ");
Console.BackgroundColor = ConsoleColor.White;
Console.Write("        ");
Console.BackgroundColor = ConsoleColor.Black;
Console.Write(" ");
Console.BackgroundColor = ConsoleColor.White;
Console.Write("    ");
Console.BackgroundColor = ConsoleColor.Black;
Console.WriteLine();
Console.BackgroundColor = ConsoleColor.White;
Console.Write("     ");
Console.BackgroundColor = ConsoleColor.Black;
Console.Write("        ");
Console.BackgroundColor = ConsoleColor.White;
Console.Write("     ");
Console.BackgroundColor = ConsoleColor.Black;
Console.WriteLine();
Console.BackgroundColor = ConsoleColor.White;
Console.Write("                  ");
Console.BackgroundColor = ConsoleColor.Black;
Console.WriteLine();